### PR TITLE
Rancher work

### PR DESCRIPTION
**Pull request by yasker**

### CODE REVIEW

**Comment by os12** [comment]
BTW, do you have any other patches from Maxim? I vaguely remember something about allocator and the async mode...

**Comment by yasker** [comment]
This is all I have except the debug patch: https://github.com/yasker/linux/commits/work

I don't know if everyone of them has been included since you squash the commits...

**Comment by os12** [comment]
Here is the last one. Could you have a look please?

https://bitbucket.org/mkhon/target-pending/commits/eed0293fe91ddfe59bd9fa57b98ecf13a87eb19a?at=master

**Comment by yasker** [comment]
Your tree has all of them except the disable of async bit, which is not function impacted as long as you're setting the flag.

**Pull request merged**
